from pydantic import Field, validator
from typing import List, Optional, Union, Literal
from sdks.novavision.src.base.model import Package, Image, Inputs, Configs, Outputs, Response, Request, Output, Input, Config, Detection


class InputImage(Input):
    """The source image for the GMM segmentation process."""
    name: Literal["inputImage"] = "inputImage"
    value: Union[List[Image], Image]
    type: str = "object"

    @validator("type", pre=True, always=True)
    def set_type_based_on_value(cls, value, values):
        value = values.get('value')
        if isinstance(value, Image):
            return "object"
        elif isinstance(value, list):
            return "list"

    class Config:
        title = "Image"
        json_schema_extra = {"shortDescription": "Input Image Source"}


class ClusterMask(Detection):
    """GMM component metadata and RLE-encoded mask data."""
    cluster_id: int
    mask_rle: List[int]
    box_2d: List[int]
    imgUID: str
    color: str


class OutputData(Output):
    """The list of GMM component masks generated by the algorithm."""
    name: Literal["outputData"] = "outputData"
    value: List[ClusterMask] = []
    type: Literal["list"] = "list"

    class Config:
        title = "GMM Component Masks"
        json_schema_extra = {"shortDescription": "Extracted GMM Mask Metadata"}


class NumComponents(Config):
    name: Literal["numComponents"] = "numComponents"
    value: int = Field(default=2)
    type: Literal["number"] = "number"
    field: Literal["textInput"] = "textInput"

    class Config:
        title = "Number of Components"
        json_schema_extra = {"shortDescription": "Gaussian component count"}


class PointX(Config):
    name: Literal["pointX"] = "pointX"
    value: int = Field(default=0)
    type: Literal["number"] = "number"
    field: Literal["textInput"] = "textInput"

    class Config:
        title = "Point X"
        json_schema_extra = {"shortDescription": "X coordinate of the seed point"}


class PointY(Config):
    name: Literal["pointY"] = "pointY"
    value: int = Field(default=0)
    type: Literal["number"] = "number"
    field: Literal["textInput"] = "textInput"

    class Config:
        title = "Point Y"
        json_schema_extra = {"shortDescription": "Y coordinate of the seed point"}


class OptionFull(Config):
    name: Literal["optionFull"] = "optionFull"
    NumComponents: NumComponents
    value: Literal["FULL"] = "FULL"
    type: Literal["string"] = "string"
    field: Literal["option"] = "option"

    class Config:
        title = "Full Image"
        json_schema_extra = {"shortDescription": "Process entire frame, return all components"}


class OptionPoint(Config):
    name: Literal["optionPoint"] = "optionPoint"
    NumComponents: NumComponents
    PointX: PointX
    PointY: PointY
    value: Literal["POINT"] = "POINT"
    type: Literal["string"] = "string"
    field: Literal["option"] = "option"

    class Config:
        title = "Point Prompt"
        json_schema_extra = {"shortDescription": "Return component at clicked pixel"}


class ConfigGmmMode(Config):
    name: Literal["configGmmMode"] = "configGmmMode"
    value: Union[OptionFull, OptionPoint]
    type: Literal["object"] = "object"
    field: Literal["dependentDropdownlist"] = "dependentDropdownlist"

    class Config:
        title = "Segmentation Mode"
        json_schema_extra = {"shortDescription": "Spatial strategy selection"}


class GmmConfigs(Configs):
    configGmmMode: ConfigGmmMode


class GmmInputs(Inputs):
    inputImage: InputImage


class GmmOutputs(Outputs):
    outputData: OutputData


class GmmRequest(Request):
    inputs: Optional[GmmInputs]
    configs: GmmConfigs

    class Config:
        json_schema_extra = {"target": "configs"}


class GmmResponse(Response):
    outputs: GmmOutputs


class GmmExecutor(Config):
    name: Literal["Gmm"] = "Gmm"
    value: Union[GmmRequest, GmmResponse]
    type: Literal["object"] = "object"
    field: Literal["option"] = "option"

    class Config:
        title = "GMM Segmenter"
        json_schema_extra = {"shortDescription": "Gaussian Mixture Model Engine", "target": {"value": 0}}


class ConfigExecutor(Config):
    name: Literal["ConfigExecutor"] = "ConfigExecutor"
    value: Union[GmmExecutor]
    type: Literal["executor"] = "executor"
    field: Literal["dependentDropdownlist"] = "dependentDropdownlist"

    class Config:
        title = "Algorithm"
        json_schema_extra = {"shortDescription": "Selected Logic Engine", "target": "value"}


class PackageConfigs(Configs):
    executor: ConfigExecutor


class PackageModel(Package):
    configs: PackageConfigs
    type: Literal["capsule"] = "capsule"
    name: Literal["CcvGmm"] = "CcvGmm"
    uID: str = "7654321"

    class Config:
        json_schema_extra = {"shortDescription": "GMM Capsule Package"}
